codecov:
  branch: master

coverage:
  precision: 2
  round: nearest
  range: "50...100"
  status:
    project:
      default:
        threshold: null
    patch:
      default:
        target: 80%

comment:
  layout: "diff"

coverage:
  ignore:
    - "modules/http-server"

